language: java
sudo: false
install: true
#addons:
#  sonarcloud:
#    organization: "sahriartoufiq-github"
#    token:
#      secure: "$SONAR_TOKEN"
#addons:
#  sonarqube:
#    token:
#      secure: "$st"
jdk:
  - oraclejdk8
script:
  - mvn sonar:sonar
  # -Dsonar.host.url=http://1ae24205.ngrok.io \
      -Dsonar.host.url=http://1ae24205.ngrok.io \
      -Dsonar.login="$st"
#  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar
cache:
  directories:
    - '$HOME/.m2/repository'