version: '3.1'

services:

  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 2010332034
      MYSQL_USER: sahriar
      MYSQL_PASSWORD: 2010332034
      MYSQL_DATABASE: sp


  springpagination:
    image: sp
    restart: always
    ports:
      - 8080:8080
    depends_on:
     - db



#GRANT ALL PRIVILEGES ON *.* TO 'sahriar'@'%' IDENTIFIED BY '2010332034';



#
#
#version: '3'
#
#services:
#  demo-mysql:
#    image: mysql:latest
#    environment:
#       MYSQL_ROOT_PASSWORD: 2010332034
#       MYSQL_DATABASE: spring_pagination
#          MYSQL_ROOT_HOST: '%'
#         ports:
#         - "3306:3306"
#         restart: always
#  spring-boot-jpa-docker-webapp:
#    image: springpagination
#    depends_on:
#      - demo-mysql
#    ports:
#      - 8080:8080
#
#
#docker run --name sp --link some-mysql:mysql -d sp -p 8083:8083
#
#sudo docker run --name=spa --link=some-mysqla:mysql --publish=8083:8083 --volume=springpagination-repo:/home/toufiq sp:latest
#
#docker run -d --name demo-mysql --net=my-network -e MYSQL_ROOT_PASSWORD=2010332034 -e MYSQL_DATABASE=springpagination mysql:latest
#
#docker run -it mysql -h 127.0.0.1 -P 3306 --MYSQL_ROOT_PASSWORD=2010332034 spring-pagination
#
#
#docker run --name demo-mysql -e MYSQL_ROOT_PASSWORD=password -e MYSQL_DATABASE=demo -e MYSQL_USER=demo_user -e MYSQL_PASSWORD=demo_pass -d mysql:5.6
#
#
#docker rm $(docker ps -aq)
#
#
#docker run --name some-mysql -e MYSQL_ROOT_PASSWORD=2010332034 -e MYSQL_USER=sahriar -e MYSQL_PASSWORD=2010332034 -e MYSQL_DATABASE=sp -d mysql:latest
#
#
# sudo docker run --name=sp --link=some-mysql:mysql --publish=8083:8083 --volume=springpagination-repo:/home/toufiq sp:latest

#sudo docker run --name=sp --add-host=dbhost:`/sbin/ip route|awk '/default/ { print  $3}'` --publish=8083:8083 --volume=springpagination-repo:/home/toufiq sp:latest



#sudo docker  run --name=sp -e "SPRING_PROFILES_ACTIVE=container" -p 8888:8888 springpagination

